### ISSUE TITLE
Dimensionality

### ISSUE THREAD

**Issue by dezenn** [MatthiasKi/SobolevTrainingApproxDerivatives#1]
Dear researchers and developers, 

your code is currently written for functions with two dimensional input and one dimensional output, as you also stated clearly in your paper. 
Am I going to face any issues when modifying your code such that it works for multidimensional in- and output? Any issues regarding technical aspects, i.e. taking the derivative and/or theoretical aspects? Is there a theoretical reason you did not study multidimensional cases in your paper? Thanks in advance.

Best regards.

**Comment by MatthiasKi** [comment]
Dear dezenn,

I don't think that there would be major problems for modifying the code such that it works for multidimensional in-and outputs. Indeed, we ran some experiments on real-world data sets with multidimensional inputs (as discussed in the paper). However, unfortunately, I can't find the code we used for the multidimensional experiments anymore. 

Best regards,
Matthias

**Comment by dezenn** [comment]
Dear Matthias,

thank you very much for your kind and honest answer. It is reason enough for me that I am going to try the multidimensional case.

Best regards, 
Dean
